import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "web", "src", "generated");
mkdirSync(outDir, { recursive: true });

const abiOf = (name) =>
  JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8")).abi;

const deployments = JSON.parse(
  readFileSync(join(root, "contracts", "deployments", "local.json"), "utf8"),
);

const banner = "// Generated by scripts/sync-abi.mjs. Do not edit by hand.\n";
const asConst = (name, value) => `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;

writeFileSync(
  join(outDir, "contracts.ts"),
  banner +
    asConst("addresses", deployments) +
    asConst("erc20Abi", abiOf("MockERC20")) +
    asConst("ammAbi", abiOf("SimpleAMM")) +
    asConst("veilSwapAbi", abiOf("VeilSwap")) +
    asConst("batchVeilSwapAbi", abiOf("BatchVeilSwap")),
);

console.log("synced ABIs + addresses ->", join(outDir, "contracts.ts"));
